language: node_js

branches:
  only: 
   - master

node_js:
 - '0.10.48'
 - '4.0'
 - '5.11'
 - '6.3.0'
 - '6.6.0'
 - '7.1.0'
 - 'node'

env:
 - MOCHA_VERSION=*

matrix:
  exclude:
    - node_js: 0.10.48
      env: MOCHA_VERSION=*
  include:
    - node_js: 0.10.48
      env: MOCHA_VERSION=3.5.*

before_install:
 # npmjs changed CA and broke old versions since nodejs doesn't have the system certificate store? for shame.
 - echo ${TRAVIS_NODE_VERSION}
 - |
     if [ "${TRAVIS_NODE_VERSION}" = "0.10.0" ]; then
         npm config set ca null && echo "npm - disabled strict-ssl"
     fi

script:
 - npm install mocha@$MOCHA_VERSION
 - node ./node_modules/jshint/bin/jshint main.js lib/ test/
 - node ./node_modules/jscs/bin/jscs main.js lib/ test/
 - npm test
